# Generated by Django 3.0.3 on 2020-02-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200226_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, to='api.Board'),
        ),
    ]
