# Generated by Django 3.0.3 on 2020-02-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=12)),
                ('password', models.CharField(max_length=128)),
                ('email', models.CharField(db_index=True, max_length=128)),
                ('verification', models.BooleanField()),
                ('verification_key', models.CharField(max_length=128)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('is_superuser', models.BooleanField()),
                ('last_login', models.DateTimeField()),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('date_joined', models.DateTimeField()),
                ('profile_photo', models.CharField(max_length=4096)),
            ],
        ),
    ]
