# Generated by Django 3.0.3 on 2020-02-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_up_api', '0002_auto_20200226_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='bookmarks',
            field=models.ManyToManyField(null=True, to='dev_up_api.Board'),
        ),
    ]
